spring.application.name=${SPRING_APPLICATION_NAME}

# AWS EB??? SERVER_PORT=5000
# ????? ???? ??? 8081

server.port=${SERVER_PORT}

# DB
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

# MyBatis
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

# SQL ???
spring.sql.init.mode=${SPRING_SQL_INIT_MODE}
spring.sql.init.schema-locations=${SPRING_SQL_INIT_SCHEMA_LOCATIONS}
spring.sql.init.continue-on-error=${SPRING_SQL_INIT_CONTINUE_ON_ERROR}

# ?? ?? API
owner.server.base-url=${OWNER_SERVER_BASE_URL}

# Redis
spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}

# Kafka? ???? ?? ????
app.kafka.enabled=${APP_KAFKA_ENABLED}

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.consumer.group-id=${SPRING_KAFKA_CONSUMER_GROUP_ID}
spring.kafka.consumer.auto-offset-reset=${SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET}
spring.kafka.consumer.properties.spring.json.trusted.packages=${SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_TRUSTED_PACKAGES}
spring.kafka.producer.acks=${SPRING_KAFKA_PRODUCER_ACKS}
spring.kafka.producer.retries=${SPRING_KAFKA_PRODUCER_RETRIES}


# QR / ?? URL
app.frontend.review-base-url=${APP_FRONTEND_REVIEW_BASE_URL}
app.qr.save-dir=${APP_QR_SAVE_DIR}
app.qr.public-prefix=${APP_QR_PUBLIC_PREFIX}

spring.ai.openai.api-key=${SPRING_AI_OPENAI_API_KEY}
spring.ai.openai.chat.options.model=${SPRING_AI_OPENAI_CHAT_OPTIONS_MODEL:gpt-4o-mini}